name: flutter_skeleton_ui
description: A Flutter package for building custom skeleton widgets to mimic the page's layout while loading.
version: 0.0.5
homepage: https://github.com/jordanliu/flutter_skeletons_ui

environment:
  sdk: ">=2.12.0 <3.22.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
